# Generated by Django 6.0.2 on 2026-04-24 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('nascimento', models.DateField()),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('usuario', models.OneToOneField(db_column='id_usuarios', on_delete=django.db.models.deletion.CASCADE, related_name='credencial', to='api_usuario.usuario')),
            ],
            options={
                'db_table': 'credenciais',
            },
        ),
    ]
