# Generated by Django 6.0.2 on 2026-03-24 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'credenciais',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('nascimento', models.DateField()),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='ResetSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('credencial', models.ForeignKey(db_column='id_credenciais', on_delete=django.db.models.deletion.CASCADE, related_name='reset_senha', to='api_usuario.credencial')),
            ],
            options={
                'db_table': 'reset_senha',
            },
        ),
        migrations.CreateModel(
            name='TokenVerificacaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('verificado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(db_column='id_usuarios', on_delete=django.db.models.deletion.CASCADE, related_name='tokens_verificacao_email', to='api_usuario.usuario')),
            ],
            options={
                'db_table': 'tokens_verificacao_email',
            },
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif', models.BinaryField()),
                ('descricao', models.TextField()),
                ('usuario', models.ForeignKey(db_column='id_usuarios', on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to='api_usuario.usuario')),
            ],
            options={
                'db_table': 'postagens',
            },
        ),
        migrations.AddField(
            model_name='credencial',
            name='usuario',
            field=models.OneToOneField(db_column='id_usuarios', on_delete=django.db.models.deletion.CASCADE, related_name='credencial', to='api_usuario.usuario'),
        ),
    ]
