# Generated by Django 6.0.2 on 2026-03-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='aniversario',
            new_name='nascimento',
        ),
    ]
