# Generated by Django 6.0.2 on 2026-05-01 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSentimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif_url', models.URLField(blank=True, max_length=500, null=True)),
                ('texto_sentimento', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='id_usuarios', on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to='api_usuario.usuario')),
            ],
            options={
                'db_table': 'postagens',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Reacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reacao_tipo', models.CharField(max_length=50)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='api_postagem.postsentimento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes_feitas', to='api_usuario.usuario')),
            ],
            options={
                'db_table': 'reacoes',
                'unique_together': {('usuario', 'postagem')},
            },
        ),
    ]
